# Generated by Django 5.2.4 on 2025-07-25 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.destino'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='po',
            field=models.CharField(max_length=50, verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('liberado', 'Liberado')], default='aguardando', max_length=10),
        ),
    ]
