# Generated by Django 5.2.4 on 2025-07-25 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_destino_options_alter_lancamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={},
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destino'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='po',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='status',
            field=models.CharField(choices=[('liberado', 'Liberado'), ('aguardando', 'Aguardando')], max_length=20),
        ),
    ]
