# Generated by Django 5.2.4 on 2025-07-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_destino_options_alter_lancamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('azul', 'Azul')], default='claro', max_length=20)),
            ],
        ),
    ]
