# Generated by Django 5.2.4 on 2025-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaodashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='po',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
