# Generated by Django 5.2.4 on 2025-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lancamento_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='po',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='status',
            field=models.CharField(choices=[('liberado', 'Liberado'), ('aguardando', 'Aguardando'), ('finalizado', 'Finalizado')], max_length=20),
        ),
    ]
