# Generated by Django 5.2.4 on 2025-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paranagua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='po',
            field=models.CharField(max_length=15),
        ),
    ]
