# Generated by Django 5.2.4 on 2025-09-13 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(choices=[('ibipora', 'Ibiporã'), ('paranagua', 'Paranaguá'), ('rondonopolis', 'Rondonópolis')], max_length=20, unique=True)),
                ('app_django', models.CharField(default='core', max_length=50)),
                ('url_inicial', models.CharField(default='/', max_length=100)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiais', models.ManyToManyField(blank=True, related_name='usuarios_com_acesso', to='usuarios.filial')),
                ('filial_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_selecionados', to='usuarios.filial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
