"""
Django settings for painel project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import os
from dotenv import load_dotenv

# Carregar variáveis de ambiente do arquivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h*qsm%4q^azw!s(0i3^$qaklp42pwtwnivb10m8i8h-_rbsy!n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['portorestrito.pythonanywhere.com', '127.0.0.1', 'localhost', '192.168.68.109', '*']

# Adicionar o hostname da Azure dinamicamente, se existir
website_hostname = os.environ.get('WEBSITE_HOSTNAME')
if website_hostname:
    ALLOWED_HOSTS.append(website_hostname)

# Permitir CSRF de origens da rede local
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.68.109:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

if website_hostname:
    CSRF_TRUSTED_ORIGINS.append(f"https://{website_hostname}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'core',
    'usuarios',
    'paranagua',
    'rondonopolis',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'painel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.filiais_context',
                'rondonopolis.context_processors.grupos_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'painel.wsgi.application'
ASGI_APPLICATION = 'painel.asgi.application'

# Configuração do Channel Layer (usando InMemoryChannelLayer para desenvolvimento)
# Para produção, considere usar Redis: CHANNEL_LAYERS = {'default': {'BACKEND': 'channels_redis.core.RedisChannelLayer', 'CONFIG': {'hosts': [('127.0.0.1', 6379)],},},}}
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração do banco de dados
# Por padrão usa MySQL, mas pode usar SQLite para desenvolvimento local
USE_MYSQL = os.getenv('USE_MYSQL', 'True').lower() == 'true'

if USE_MYSQL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'seu_banco_mysql'),
            'USER': os.getenv('DB_USER', 'seu_usuario_mysql'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'sua_senha_mysql'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
            # Otimização: Reutilizar conexões por 5 minutos (reduz latência)
            'CONN_MAX_AGE': 300,
        }
    }
else:
    # SQLite para desenvolvimento local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Fuso horário de Rondonópolis (Mato Grosso)
# Os horários são salvos diretamente no horário de Rondonópolis no banco
TIME_ZONE = 'America/Cuiaba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Pasta de desenvolvimento onde você mantém os arquivos
STATICFILES_DIRS = [BASE_DIR / 'static']

# Pasta para onde o collectstatic vai copiar tudo em produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: arquivos estáticos com cache e compressão otimizados
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'digitalmidia@transcamila.com.br')
# EMAIL_HOST_PASSWORD: usar .env em produção, fallback temporário apenas para desenvolvimento local
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'lwyz zeti nhtu uypd' if DEBUG else '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

MESSAGE_TAGS = {
    messages.SUCCESS: 'alert-success',
    messages.ERROR: 'alert-danger',
    messages.WARNING: 'alert-warning',
    messages.INFO: 'alert-info',
}

# URLs para reset de senha
LOGIN_URL = 'login'

PASSWORD_RESET_TIMEOUT = 120

# Configurações do WhatsApp API
# Para usar Evolution API ou outras APIs gratuitas de WhatsApp
WHATSAPP_API_URL = os.getenv('WHATSAPP_API_URL', '')
WHATSAPP_API_KEY = os.getenv('WHATSAPP_API_KEY', '')
WHATSAPP_API_INSTANCE = os.getenv('WHATSAPP_API_INSTANCE', 'default')

# Configurações Web Push (VAPID Keys)
# Para gerar as chaves, execute: python -m py_vapid generate_keys
# Ou use um gerador online: https://web-push-codelab.glitch.me/
VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.getenv('VAPID_PRIVATE_KEY', '')
VAPID_CLAIMS = {
    "sub": "mailto:digitalmidia@transcamila.com.br"
}

# Cache para melhorar performance (reduz queries repetitivas)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # Cache por 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Force reload
