# Generated by Django 5.2.4 on 2025-10-01 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(db_index=True, max_length=50, unique=True)),
                ('motorista', models.CharField(max_length=100)),
                ('data_agendada', models.DateField()),
                ('horario_agendado', models.TimeField()),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('entrega', 'Entrega')], max_length=10)),
                ('placa_veiculo', models.CharField(max_length=8)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_veiculo', models.CharField(choices=[('truck', 'Truck'), ('carreta', 'Carreta'), ('bitrem', 'Bitrem'), ('rodotrem', 'Rodotrem'), ('vuc', 'VUC'), ('toco', 'Toco'), ('ls', 'LS')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rondonopolis.transportadora')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendada', 'horario_agendado'],
            },
        ),
    ]
