# Generated by Django 5.2.4 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_chegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes_portaria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Confirmação'), ('confirmado', 'Confirmado'), ('atrasado', 'Atrasado'), ('finalizado', 'Finalizado')], default='aguardando', max_length=20),
        ),
    ]
