# Generated by Django 5.2.4 on 2025-10-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0003_agendamento_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Chegada'), ('chegada_confirmada', 'Chegada Confirmada'), ('liberado', 'Liberado'), ('atrasado', 'Atrasado')], default='aguardando', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data_agendada', 'status'], name='rondonopoli_data_ag_52988a_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['horario_saida'], name='rondonopoli_horario_c723ce_idx'),
        ),
    ]
