# Generated by Django 5.2.8 on 2025-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0004_alter_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data_agendada', 'horario_agendado'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='rondonopoli_data_ag_52988a_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='rondonopoli_horario_c723ce_idx',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario_chegada',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario_saida',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes_portaria',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='armazem_chegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Armazém - Data/Hora de Chegada'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checklist_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checklist - Data/Hora Preenchimento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checklist_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Checklist - Número'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checklist_observacao',
            field=models.TextField(blank=True, verbose_name='Checklist - Observação'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='onda_liberacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onda - Data/Hora da Liberação'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='onda_status',
            field=models.CharField(choices=[('aguardando', 'AGUARDANDO'), ('liberado', 'LIBERADO')], default='aguardando', max_length=20, verbose_name='Onda - Status'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='portaria_liberacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Portaria - Data/Hora Liberação'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_geral',
            field=models.CharField(choices=[('aguardando_chegada', 'Aguardando Chegada'), ('em_checklist', 'Em CheckList'), ('confirmacao_armazem', 'Confirmação Armazém'), ('pendente_liberacao_onda', 'Pendente de Liberação Onda'), ('processo_concluido', 'Processo Concluído')], default='aguardando_chegada', max_length=30, verbose_name='Status Geral do Processo'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendada',
            field=models.DateField(verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_agendado',
            field=models.TimeField(verbose_name='Horário Agendado'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='ordem',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Ordem/Nº Importação'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='placa_veiculo',
            field=models.CharField(max_length=8, verbose_name='Placa do Veículo'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['ordem'], name='rondonopoli_ordem_733e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['status_geral'], name='rondonopoli_status__180772_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data_agendada', 'horario_agendado'], name='rondonopoli_data_ag_951f7f_idx'),
        ),
    ]
