# Generated by Django 5.2.8 on 2025-11-18 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0005_alter_agendamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agendamento',
            name='rondonopoli_data_ag_951f7f_idx',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='armazem_confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes_armazem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='checklist_preenchido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_preenchidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='onda_liberado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_onda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='portaria_liberado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_portaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='armazem_chegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Armazém - Data/Hora da Chegada'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='checklist_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CheckList - Data/Hora do Preenchimento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='checklist_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do CheckList'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='checklist_observacao',
            field=models.TextField(blank=True, verbose_name='Observação do CheckList'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motorista',
            field=models.CharField(max_length=100, verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='onda_status',
            field=models.CharField(choices=[('aguardando', 'AGUARDANDO'), ('liberado', 'LIBERADO')], default='aguardando', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='placa_veiculo',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='portaria_liberacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Portaria - Data/Hora da Liberação'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status_geral',
            field=models.CharField(choices=[('aguardando_chegada', 'Aguardando Chegada'), ('em_checklist', 'Em CheckList'), ('confirmacao_armazem', 'Confirmação Armazém'), ('pendente_liberacao_onda', 'Pendente de Liberação Onda'), ('processo_concluido', 'Processo Concluído')], db_index=True, default='aguardando_chegada', max_length=30, verbose_name='Status Geral'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('coleta', 'Coleta'), ('entrega', 'Entrega')], max_length=10, verbose_name='Tipo Operação'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_veiculo',
            field=models.CharField(choices=[('truck', 'Truck'), ('carreta', 'Carreta'), ('bitrem', 'Bitrem'), ('rodotrem', 'Rodotrem'), ('vuc', 'VUC'), ('toco', 'Toco'), ('ls', 'LS')], max_length=20, verbose_name='Tipo de Veículo'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='rondonopolis.transportadora'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data_agendada'], name='rondonopoli_data_ag_ced5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['placa_veiculo'], name='rondonopoli_placa_v_66fa16_idx'),
        ),
    ]
