# Generated by Django 5.2.8 on 2025-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0006_remove_agendamento_rondonopoli_data_ag_951f7f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='checklist_observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
