# Generated by Django 5.2.8 on 2025-11-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0007_alter_agendamento_checklist_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'indexes': [models.Index(fields=['nome'], name='rondonopoli_nome_140ccc_idx')],
            },
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='rondonopolis.motorista'),
        ),
    ]
