# Generated by Django 5.2.8 on 2025-12-10 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0008_motorista_alter_agendamento_motorista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('armazem', 'Armazém'), ('administracao', 'Administração')], max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='grupos_rondonopolis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Usuário',
                'verbose_name_plural': 'Grupos de Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aba', models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('armazem', 'Armazém'), ('agendamentos', 'Agendamentos'), ('processos', 'Processos'), ('dashboard', 'Dashboard'), ('painel', 'Painel')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no menu')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abas', to='rondonopolis.grupousuario')),
            ],
            options={
                'verbose_name': 'Aba do Grupo',
                'verbose_name_plural': 'Abas dos Grupos',
                'ordering': ['grupo', 'ordem', 'aba'],
                'unique_together': {('grupo', 'aba')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('armazem', 'Armazém'), ('onda', 'Onda')], max_length=20)),
                ('email_destinatario', models.EmailField(help_text='Email para receber notificações desta etapa', max_length=254)),
                ('whatsapp_destinatario', models.CharField(blank=True, help_text='Número WhatsApp (formato: 5511999999999)', max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_notificacao', to='rondonopolis.grupousuario')),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificações',
                'ordering': ['grupo', 'etapa'],
                'unique_together': {('grupo', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('navegador', 'Notificação Navegador')], max_length=20)),
                ('destinatario', models.CharField(help_text='Email ou número WhatsApp', max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('mensagem', models.TextField(help_text='Conteúdo da notificação')),
                ('enviado_com_sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('etapa_quando_enviado', models.CharField(help_text='Etapa do processo quando foi enviado', max_length=30)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='rondonopolis.agendamento')),
            ],
            options={
                'verbose_name': 'Notificação de Processo',
                'verbose_name_plural': 'Notificações de Processos',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['agendamento', 'tipo'], name='rondonopoli_agendam_7e27ed_idx'), models.Index(fields=['enviado_em'], name='rondonopoli_enviado_6dd58b_idx')],
            },
        ),
    ]
