# Generated by Django 5.2.8 on 2025-12-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deletar_configuracoes_antigas(apps, schema_editor):
    """Deleta todas as configurações antigas antes de alterar a estrutura"""
    ConfiguracaoNotificacao = apps.get_model('rondonopolis', 'ConfiguracaoNotificacao')
    ConfiguracaoNotificacao.objects.all().delete()


def reverse_deletar_configuracoes_antigas(apps, schema_editor):
    """Função reversa (não faz nada)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0009_grupousuario_grupoaba_configuracaonotificacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Deletar registros antigos primeiro
        migrations.RunPython(deletar_configuracoes_antigas, reverse_deletar_configuracoes_antigas),
        migrations.AlterModelOptions(
            name='configuracaonotificacao',
            options={'ordering': ['usuario__username'], 'verbose_name': 'Configuração de Notificação', 'verbose_name_plural': 'Configurações de Notificações'},
        ),
        migrations.AlterUniqueTogether(
            name='configuracaonotificacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuário que receberá as notificações', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_notificacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='email_destinatario',
            field=models.EmailField(help_text='Email para receber notificações (configurado pelo administrador)', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='whatsapp_destinatario',
            field=models.CharField(blank=True, help_text='Número WhatsApp (formato: 5511999999999) - configurado pelo administrador', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_email', models.BooleanField(default=True, help_text='Receber notificações por email')),
                ('receber_whatsapp', models.BooleanField(default=True, help_text='Receber notificações por WhatsApp')),
                ('receber_navegador', models.BooleanField(default=True, help_text='Receber notificações do navegador')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuário que configura suas preferências', on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificações',
            },
        ),
        migrations.RemoveField(
            model_name='configuracaonotificacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='configuracaonotificacao',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='configuracaonotificacao',
            name='grupo',
        ),
    ]
