# Generated by Django 5.2.8 on 2025-12-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0016_adicionar_grupo_monitores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tela', models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('onda', 'Liberacao de Onda'), ('armazem', 'Armazem'), ('liberacao_documentos', 'Documentos'), ('agendamentos', 'Agendamentos (Lista)'), ('dashboard', 'Dashboard'), ('painel', 'Painel TV')], db_index=True, max_length=50, unique=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Controle de Atualizacao',
                'verbose_name_plural': 'Controle de Atualizacoes',
            },
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='usuario',
            field=models.OneToOneField(help_text='Usuário que receberá as notificações', on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_notificacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupoaba',
            name='aba',
            field=models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('armazem', 'Armazém'), ('onda', 'Liberação de Onda'), ('liberacao_documentos', 'Documentos'), ('agendamentos', 'Agendamentos'), ('processos', 'Processos'), ('dashboard', 'Dashboard'), ('painel', 'Painel')], max_length=20),
        ),
    ]
