# Generated by Django 5.2.8 on 2026-01-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0017_controleatualizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='armazem_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Armazém - Data/Hora da Saída'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='armazem_saida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_armazem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controleatualizacao',
            name='tela',
            field=models.CharField(choices=[('portaria', 'Portaria'), ('checklist', 'CheckList'), ('onda', 'Liberacao de Onda'), ('armazem', 'Armazem'), ('armazem', 'Armazem'), ('liberacao-documentos', 'Documentos'), ('liberacao_documentos', 'Documentos (Legacy)'), ('agendamentos', 'Agendamentos (Lista)'), ('dashboard', 'Dashboard'), ('painel', 'Painel TV')], db_index=True, max_length=50, unique=True),
        ),
    ]
