# Generated by Django 5.2.8 on 2026-01-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0018_agendamento_armazem_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status_geral',
            field=models.CharField(choices=[('aguardando_chegada', 'Aguardando Chegada'), ('em_checklist', 'Em CheckList'), ('confirmacao_armazem', 'Confirmação Armazém'), ('em_operacao_armazem', 'Em Operação no Armazém'), ('pendente_liberacao_onda', 'Pendente de Liberação Onda'), ('pendente_liberacao_documentos', 'Pendente Liberação Documentos'), ('processo_concluido', 'Processo Concluído')], db_index=True, default='aguardando_chegada', max_length=30, verbose_name='Status Geral'),
        ),
    ]
