# Generated by Django 5.2.8 on 2026-01-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0019_alter_agendamento_status_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='armazem_saida_observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Armazém - Observação Saída'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='documentos_observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Documentos - Observação Liberação'),
        ),
    ]
