# Generated by Django 5.2.8 on 2026-01-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondonopolis', '0020_agendamento_armazem_saida_observacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='portaria_chegada_armazem',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Portaria - Confirmou Chegada Armazém'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='portaria_chegada_armazem_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes_chegada_armazem_portaria', to=settings.AUTH_USER_MODEL),
        ),
    ]
